version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: tailwindcss
    versions:
    - 2.1.1
    - 2.1.2
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.6
    - 8.2.8
    - 8.2.9
  - dependency-name: cssnano
    versions:
    - 4.1.11
    - 5.0.0
    - 5.0.1
